// @flow

export const SOCKET_CONN_REQUEST: "SOCKET/SOCKET_CONN_REQUEST" =
  "SOCKET/SOCKET_CONN_REQUEST";
export const SOCKET_CONN_START: "SOCKET/SOCKET_CONN_START" =
  "SOCKET/SOCKET_CONN_START";
export const SOCKET_CONN_SUCCESS: "SOCKET/SOCKET_CONN_SUCCESS" =
  "SOCKET/SOCKET_CONN_SUCCESS";
export const SOCKET_CONN_END: "SOCKET/SOCKET_CONN_END" =
  "SOCKET/SOCKET_CONN_END";
export const SOCKET_CONN_FAIL: "SOCKET/SOCKET_CONN_FAIL" =
  "SOCKET/SOCKET_CONN_FAIL";

export const SOCKET_AUTH_SUCCESS: "SOCKET/SOCKET_AUTH_SUCCESS" =
  "SOCKET/SOCKET_AUTH_SUCCESS";

export const SOCKET_CHECKPOINT_REQUIRED: "SOCKET/SOCKET_CHECKPOINT_REQUIRED" =
  "SOCKET/SOCKET_CHECKPOINT_REQUIRED";
