// @flow

export const SIGN_IN_REQUEST: "AUTH/SIGN_IN_REQUEST" = "AUTH/SIGN_IN_REQUEST";
export const SIGN_IN_START: "AUTH/SIGN_IN_START" = "AUTH/SIGN_IN_START";
export const SIGN_IN_SUCCESS: "AUTH/SIGN_IN_SUCCESS" = "AUTH/SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL: "AUTH/SIGN_IN_FAIL" = "AUTH/SIGN_IN_FAIL";

export const SIGN_UP_REQUEST: "AUTH/SIGN_UP_REQUEST" = "AUTH/SIGN_UP_REQUEST";
export const SIGN_UP_START: "AUTH/SIGN_UP_START" = "AUTH/SIGN_UP_START";
export const SIGN_UP_SUCCESS: "AUTH/SIGN_UP_SUCCESS" = "AUTH/SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL: "AUTH/SIGN_UP_FAIL" = "AUTH/SIGN_UP_FAIL";

export const SIGN_OUT_REQUEST: "AUTH/SIGN_OUT_REQUEST" =
  "AUTH/SIGN_OUT_REQUEST";
export const SIGN_OUT_START: "AUTH/SIGN_OUT_START" = "AUTH/SIGN_OUT_START";
export const SIGN_OUT_SUCCESS: "AUTH/SIGN_OUT_SUCCESS" =
  "AUTH/SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAIL: "AUTH/SIGN_OUT_FAIL" = "AUTH/SIGN_OUT_FAIL";

export const CLEAR_AUTH_ERROR: "AUTH/CLEAR_AUTH_ERROR" =
  "AUTH/CLEAR_AUTH_ERROR";

// Socials Auth

export const GOOGLE_SIGN_IN_REQUEST: "AUTH/GOOGLE_SIGN_IN_REQUEST" =
  "AUTH/GOOGLE_SIGN_IN_REQUEST";
export const GOOGLE_SIGN_IN_START: "AUTH/GOOGLE_SIGN_IN_START" =
  "AUTH/GOOGLE_SIGN_IN_START";
export const GOOGLE_SIGN_IN_SUCCESS: "AUTH/GOOGLE_SIGN_IN_SUCCESS" =
  "AUTH/GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAIL: "AUTH/GOOGLE_SIGN_IN_FAIL" =
  "AUTH/GOOGLE_SIGN_IN_FAIL";
