// @flow

export const CONN_ACC_REQUEST: "INST/CONN_ACC_REQUEST" =
  "INST/CONN_ACC_REQUEST";
export const CONN_ACC_START: "INST/CONN_ACC_START" = "INST/CONN_ACC_START";
export const CONN_ACC_SUCCESS: "INST/CONN_ACC_SUCCESS" =
  "INST/CONN_ACC_SUCCESS";
export const CONN_ACC_FAIL: "INST/CONN_ACC_FAIL" = "INST/CONN_ACC_FAIL";

export const FETCH_ACCS_REQUEST: "INST/FETCH_ACCS_REQUEST" =
  "INST/FETCH_ACCS_REQUEST";
export const FETCH_ACCS_START: "INST/FETCH_ACCS_START" =
  "INST/FETCH_ACCS_START";
export const FETCH_ACCS_SUCCESS: "INST/FETCH_ACCS_SUCCESS" =
  "INST/FETCH_ACCS_SUCCESS";
export const FETCH_ACCS_FAIL: "INST/FETCH_ACCS_FAIL" = "INST/FETCH_ACCS_FAIL";

export const CLEAR_CONN_ERROR: "INST/CLEAR_CONN_ERROR" =
  "INST/CLEAR_CONN_ERROR";

// *** Tasks ***

export const FETCH_TASKS_REQUEST: "INST/FETCH_TASKS_REQUEST" =
  "INST/FETCH_TASKS_REQUEST";
export const FETCH_TASKS_START: "INST/FETCH_TASKS_START" =
  "INST/FETCH_TASKS_START";
export const FETCH_TASKS_SUCCESS: "INST/FETCH_TASKS_SUCCESS" =
  "INST/FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAIL: "INST/FETCH_TASKS_FAIL" =
  "INST/FETCH_TASKS_FAIL";

export const TASK_START_REQUEST: "INST/TASK_START_REQUEST" =
  "INST/TASK_START_REQUEST";
export const TASK_START_START: "INST/TASK_START_START" =
  "INST/TASK_START_START";
export const TASK_START_SUCCESS: "INST/TASK_START_SUCCESS" =
  "INST/TASK_START_SUCCESS";
export const TASK_START_FAIL: "INST/TASK_START_FAIL" = "INST/TASK_START_FAIL";
