// @flow

// *** Account connecting flow ***
export const REQUEST_VERIFICATION_REQUEST: "INST/REQUEST_VERIFICATION_REQUEST" =
  "INST/REQUEST_VERIFICATION_REQUEST";
export const REQUEST_VERIFICATION_START: "INST/REQUEST_VERIFICATION_START" =
  "INST/REQUEST_VERIFICATION_START";
export const REQUEST_VERIFICATION_SUCCESS: "INST/REQUEST_VERIFICATION_SUCCESS" =
  "INST/REQUEST_VERIFICATION_SUCCESS";
export const REQUEST_VERIFICATION_FAIL: "INST/REQUEST_VERIFICATION_FAIL" =
  "INST/REQUEST_VERIFICATION_FAIL";

export const SET_VERIFICATION_TYPE_REQUEST: "INST/SET_VERIFICATION_TYPE_REQUEST" =
  "INST/SET_VERIFICATION_TYPE_REQUEST";
export const SET_VERIFICATION_TYPE_START: "INST/SET_VERIFICATION_TYPE_START" =
  "INST/SET_VERIFICATION_TYPE_START";
export const SET_VERIFICATION_TYPE_SUCCESS: "INST/SET_VERIFICATION_TYPE_SUCCESS" =
  "INST/SET_VERIFICATION_TYPE_SUCCESS";
export const SET_VERIFICATION_TYPE_FAIL: "INST/SET_VERIFICATION_TYPE_FAIL" =
  "INST/SET_VERIFICATION_TYPE_FAIL";

export const VERIFY_ACC_REQUEST: "INST/VERIFY_ACC_REQUEST" =
  "INST/VERIFY_ACC_REQUEST";
export const VERIFY_ACC_START: "INST/VERIFY_ACC_START" =
  "INST/VERIFY_ACC_START";
export const VERIFY_ACC_SUCCESS: "INST/VERIFY_ACC_SUCCESS" =
  "INST/VERIFY_ACC_SUCCESS";
export const VERIFY_ACC_FAIL: "INST/VERIFY_ACC_FAIL" = "INST/VERIFY_ACC_FAIL";

export const CONN_ACC_SUCCESS: "INST/CONN_ACC_SUCCESS" =
  "INST/CONN_ACC_SUCCESS";

// *** Tasks fetching ***

export const FETCH_ACCS_REQUEST: "INST/FETCH_ACCS_REQUEST" =
  "INST/FETCH_ACCS_REQUEST";
export const FETCH_ACCS_START: "INST/FETCH_ACCS_START" =
  "INST/FETCH_ACCS_START";
export const FETCH_ACCS_SUCCESS: "INST/FETCH_ACCS_SUCCESS" =
  "INST/FETCH_ACCS_SUCCESS";
export const FETCH_ACCS_FAIL: "INST/FETCH_ACCS_FAIL" = "INST/FETCH_ACCS_FAIL";

export const CLEAR_CONN_ERROR: "INST/CLEAR_CONN_ERROR" =
  "INST/CLEAR_CONN_ERROR";

// *** Tasks ***

export const FETCH_TASKS_REQUEST: "INST/FETCH_TASKS_REQUEST" =
  "INST/FETCH_TASKS_REQUEST";
export const FETCH_TASKS_START: "INST/FETCH_TASKS_START" =
  "INST/FETCH_TASKS_START";
export const FETCH_TASKS_SUCCESS: "INST/FETCH_TASKS_SUCCESS" =
  "INST/FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAIL: "INST/FETCH_TASKS_FAIL" =
  "INST/FETCH_TASKS_FAIL";

export const TASKS_START_REQUEST: "INST/TASKS_START_REQUEST" =
  "INST/TASKS_START_REQUEST";
export const TASKS_START_START: "INST/TASKS_START_START" =
  "INST/TASKS_START_START";
export const TASKS_START_SUCCESS: "INST/TASKS_START_SUCCESS" =
  "INST/TASKS_START_SUCCESS";
export const TASKS_START_FAIL: "INST/TASKS_START_FAIL" = "INST/TASKS_START_FAIL";

// *** Limits ***

export const LIMIT_UPDATE_REQUEST: "INST/LIMIT_UPDATE_REQUEST" =
  "INST/LIMIT_UPDATE_REQUEST";
export const LIMIT_UPDATE_START: "INST/LIMIT_UPDATE_START" =
  "INST/LIMIT_UPDATE_START";
export const LIMIT_UPDATE_SUCCESS: "INST/LIMIT_UPDATE_SUCCESS" =
  "INST/LIMIT_UPDATE_SUCCESS";
export const LIMIT_UPDATE_FAIL: "INST/LIMIT_UPDATE_FAIL" =
  "INST/LIMIT_UPDATE_FAIL";

// *** Stats update ***

export const STATS_UPDATE_REQUEST: "INST/STATS_UPDATE_REQUEST" =
  "INST/STATS_UPDATE_REQUEST";
export const STATS_UPDATE_START: "INST/STATS_UPDATE_START" =
  "INST/STATS_UPDATE_START";
export const STATS_UPDATE_SUCCESS: "INST/STATS_UPDATE_SUCCESS" =
  "INST/STATS_UPDATE_SUCCESS";
export const STATS_UPDATE_FAIL: "INST/STATS_UPDATE_FAIL" =
  "INST/STATS_UPDATE_FAIL";
