// @flow

export const SET_PASSWORD_REQUEST: "PASSWORD/SET_PASSWORD_REQUEST" =
  "PASSWORD/SET_PASSWORD_REQUEST";
export const SET_PASSWORD_START: "PASSWORD/SET_PASSWORD_START" =
  "PASSWORD/SET_PASSWORD_START";
export const SET_PASSWORD_SUCCESS: "PASSWORD/SET_PASSWORD_SUCCESS" =
  "PASSWORD/SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_SUCCESS_MESSAGE: "PASSWORD/SET_PASSWORD_SUCCESS_MESSAGE" =
  "PASSWORD/SET_PASSWORD_SUCCESS_MESSAGE";
export const SET_PASSWORD_SOCKET_EVENT: "PASSWORD/SET_PASSWORD_SOCKET_EVENT" =
  "PASSWORD/SET_PASSWORD_SOCKET_EVENT";
export const SET_PASSWORD_FAIL: "PASSWORD/SET_PASSWORD_FAIL" =
  "PASSWORD/SET_PASSWORD_FAIL";

export const UPDATE_PASSWORD_REQUEST: "PASSWORD/UPDATE_PASSWORD_REQUEST" =
  "PASSWORD/UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_START: "PASSWORD/UPDATE_PASSWORD_START" =
  "PASSWORD/UPDATE_PASSWORD_START";
export const UPDATE_PASSWORD_SUCCESS: "PASSWORD/UPDATE_PASSWORD_SUCCESS" =
  "PASSWORD/UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_SUCCESS_MESSAGE: "PASSWORD/UPDATE_PASSWORD_SUCCESS_MESSAGE" =
  "PASSWORD/UPDATE_PASSWORD_SUCCESS_MESSAGE";
export const UPDATE_PASSWORD_SOCKET_EVENT: "PASSWORD/UPDATE_PASSWORD_SOCKET_EVENT" =
  "PASSWORD/UPDATE_PASSWORD_SOCKET_EVENT";
export const UPDATE_PASSWORD_FAIL: "PASSWORD/UPDATE_PASSWORD_FAIL" =
  "PASSWORD/UPDATE_PASSWORD_FAIL";

export const CLEAR_MESSAGES: "PASSWORD/CLEAR_MESSAGES" =
  "PASSWORD/CLEAR_MESSAGES";

export const CHECK_PASSWORD_EXISTENCE_REQUEST: "PASSWORD/CHECK_PASSWORD_EXISTENCE_REQUEST" =
  "PASSWORD/CHECK_PASSWORD_EXISTENCE_REQUEST";
export const CHECK_PASSWORD_EXISTENCE_START: "PASSWORD/CHECK_PASSWORD_EXISTENCE_START" =
  "PASSWORD/CHECK_PASSWORD_EXISTENCE_START";
export const CHECK_PASSWORD_EXISTENCE_YES: "PASSWORD/CHECK_PASSWORD_EXISTENCE_YES" =
  "PASSWORD/CHECK_PASSWORD_EXISTENCE_YES";
export const CHECK_PASSWORD_EXISTENCE_NO: "PASSWORD/CHECK_PASSWORD_EXISTENCE_NO" =
  "PASSWORD/CHECK_PASSWORD_EXISTENCE_NO";
export const CHECK_PASSWORD_EXISTENCE_FAIL: "PASSWORD/CHECK_PASSWORD_EXISTENCE_FAIL" =
  "PASSWORD/CHECK_PASSWORD_EXISTENCE_FAIL";
