// @flow

export const POPUP_OPEN: "CONNECT-ACC-POPUP/POPUP_OPEN" =
  "CONNECT-ACC-POPUP/POPUP_OPEN";

export const POPUP_CLOSE: "CONNECT-ACC-POPUP/POPUP_CLOSE" =
  "CONNECT-ACC-POPUP/POPUP_CLOSE";

const SIGN_OUT_SUCCESS: "AUTH/SIGN_OUT_SUCCESS" = "AUTH/SIGN_OUT_SUCCESS";
