// @flow

export const POPUP_OPEN: "START-TASK-POPUP/POPUP_OPEN" =
  "START-TASK-POPUP/POPUP_OPEN";

export const POPUP_CLOSE: "START-TASK-POPUP/POPUP_CLOSE" =
  "START-TASK-POPUP/POPUP_CLOSE";

export const SEARCH_USERS_REQUEST: "START-TASK-POPUP/SEARCH_USERS_REQUEST" =
  "START-TASK-POPUP/SEARCH_USERS_REQUEST";
export const SEARCH_USERS_START: "START-TASK-POPUP/SEARCH_USERS_START" =
  "START-TASK-POPUP/SEARCH_USERS_START";
export const SEARCH_USERS_SUCCESS: "START-TASK-POPUP/SEARCH_USERS_SUCCESS" =
  "START-TASK-POPUP/SEARCH_USERS_SUCCESS";
